### ISSUE TITLE
ImportError: libpcre16.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by joshua-matt** [psuwuxian/rl_attack#9]
I've followed the steps for installing everything needed to replicate the Pong experiments, but when I try to import roboschool, I get the error message in the title. The error is thrown by line 12 of `scene_abstract.py` which tries to import `cpp_household`. I see that the `.libs` folder contains several items which have names similar to the one which apparently doesn't exist. Any ideas?

**Comment by nuwuxian** [comment]
I haven't met this error when I install the Roboschool enviroment. Maybe you could refer to this link https://github.com/openai/roboschool/issues/193.

**Comment by joshua-matt** [comment]
That thread fixed this problem! I had to install `libpcre3-dev`. In case anyone else encounters this issue, I then went on to having [this ](https://github.com/openai/roboschool/issues/212) issue, the solution to which is in the final comment of the thread. Thanks!
